import { WorkoutTemplate, TemplateCategory, ExerciseEntry } from "./types";

export const defaultTemplates: WorkoutTemplate[] = [
  // ==========================================
  // BODYWEIGHT (20 templates, tpl-001 to tpl-020)
  // ==========================================
  {
    id: "tpl-001",
    name: "Classic Push-Up Circuit",
    description: "A fundamental upper body workout using push-up variations to build chest and tricep strength.",
    category: "bodyweight",
    durationMinutes: 12,
    exercises: [
      { name: "Standard Push-Ups", type: "strength", sets: 3, reps: 15, notes: "Keep your core tight and back straight" },
      { name: "Wide-Grip Push-Ups", type: "strength", sets: 3, reps: 12, notes: "Hands wider than shoulder-width" },
      { name: "Diamond Push-Ups", type: "strength", sets: 3, reps: 10, notes: "Hands close together under your chest" },
      { name: "Incline Push-Ups", type: "strength", sets: 2, reps: 15, notes: "Use a chair or step" },
    ],
  },
  {
    id: "tpl-002",
    name: "Squat Fundamentals",
    description: "Essential lower body routine focusing on squat form and leg endurance.",
    category: "bodyweight",
    durationMinutes: 15,
    exercises: [
      { name: "Bodyweight Squats", type: "strength", sets: 4, reps: 20, notes: "Push hips back, knees over toes" },
      { name: "Sumo Squats", type: "strength", sets: 3, reps: 15, notes: "Wide stance, toes pointed out" },
      { name: "Pulse Squats", type: "strength", sets: 3, reps: 15, notes: "Stay low and pulse at the bottom" },
      { name: "Squat Hold", type: "strength", sets: 3, reps: 1, durationMinutes: 1, notes: "Hold at the bottom of the squat" },
    ],
  },
  {
    id: "tpl-003",
    name: "Walking Lunges Workout",
    description: "Dynamic lower body routine that builds leg strength and improves balance.",
    category: "bodyweight",
    durationMinutes: 18,
    exercises: [
      { name: "Walking Lunges", type: "strength", sets: 3, reps: 20, notes: "Alternate legs, keep torso upright" },
      { name: "Reverse Lunges", type: "strength", sets: 3, reps: 16, notes: "Step back and lower knee toward ground" },
      { name: "Lateral Lunges", type: "strength", sets: 3, reps: 14, notes: "Step to the side, push hips back" },
      { name: "Curtsy Lunges", type: "strength", sets: 3, reps: 12, notes: "Cross back leg behind front" },
      { name: "Lunge Hold", type: "strength", sets: 2, reps: 1, durationMinutes: 1, notes: "Hold the bottom position" },
    ],
  },
  {
    id: "tpl-004",
    name: "Tricep Dips at Home",
    description: "Upper body workout targeting triceps using a chair or bench.",
    category: "bodyweight",
    durationMinutes: 10,
    exercises: [
      { name: "Chair Dips", type: "strength", sets: 3, reps: 15, notes: "Hands on edge of chair, lower slowly" },
      { name: "Bench Dips", type: "strength", sets: 3, reps: 12, notes: "Elevate feet for added difficulty" },
      { name: "Close-Grip Push-Ups", type: "strength", sets: 3, reps: 12, notes: "Elbows close to body" },
      { name: "Tricep Extensions", type: "strength", sets: 2, reps: 15, notes: "Use a wall or sturdy surface" },
    ],
  },
  {
    id: "tpl-005",
    name: "Step-Up Power",
    description: "Builds lower body power and coordination using a sturdy step or bench.",
    category: "bodyweight",
    durationMinutes: 20,
    exercises: [
      { name: "Basic Step-Ups", type: "strength", sets: 3, reps: 20, notes: "Alternate legs, drive through heel" },
      { name: "Lateral Step-Ups", type: "strength", sets: 3, reps: 16, notes: "Step from the side of the bench" },
      { name: "Step-Up Knee Drive", type: "strength", sets: 3, reps: 14, notes: "Drive opposite knee up at the top" },
      { name: "Reverse Step-Ups", type: "strength", sets: 3, reps: 12, notes: "Step backward off the bench" },
      { name: "Single Leg Box Squat", type: "strength", sets: 2, reps: 10, notes: "Sit back onto the step on one leg" },
    ],
  },
  {
    id: "tpl-006",
    name: "Push-Up Burnout",
    description: "Intense push-up challenge with progressive variations to exhaust the chest and shoulders.",
    category: "bodyweight",
    durationMinutes: 15,
    exercises: [
      { name: "Push-Ups", type: "strength", sets: 1, reps: 25, notes: "Start with maximum reps" },
      { name: "Diamond Push-Ups", type: "strength", sets: 1, reps: 20, notes: "Hands together forming a diamond" },
      { name: "Pike Push-Ups", type: "strength", sets: 1, reps: 15, notes: "Hips high, target shoulders" },
      { name: "Decline Push-Ups", type: "strength", sets: 1, reps: 15, notes: "Feet elevated on a surface" },
      { name: "Push-Up with Rotation", type: "strength", sets: 2, reps: 12, notes: "Rotate to side plank at the top" },
    ],
  },
  {
    id: "tpl-007",
    name: "Glute Bridge Series",
    description: "Targeted glute activation routine for a stronger posterior chain.",
    category: "bodyweight",
    durationMinutes: 12,
    exercises: [
      { name: "Glute Bridges", type: "strength", sets: 3, reps: 20, notes: "Squeeze glutes at the top" },
      { name: "Single-Leg Glute Bridges", type: "strength", sets: 3, reps: 12, notes: "Keep hips level throughout" },
      { name: "Frog Bridges", type: "strength", sets: 3, reps: 15, notes: "Feet together, knees apart" },
      { name: "Glute Bridge March", type: "strength", sets: 3, reps: 16, notes: "Alternate lifting knees while bridged" },
      { name: "Hip Thrusts", type: "strength", sets: 2, reps: 15, notes: "Shoulders elevated on a bench" },
    ],
  },
  {
    id: "tpl-008",
    name: "Wall Sit Challenge",
    description: "Isometric lower body workout that builds endurance in quads and glutes.",
    category: "bodyweight",
    durationMinutes: 8,
    exercises: [
      { name: "Wall Sit", type: "strength", sets: 4, reps: 1, durationMinutes: 1, notes: "Back flat against wall, thighs parallel" },
      { name: "Single-Leg Wall Sit", type: "strength", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Extend one leg forward" },
      { name: "Wall Sit with Calf Raise", type: "strength", sets: 3, reps: 10, notes: "Rise onto toes while holding position" },
    ],
  },
  {
    id: "tpl-009",
    name: "Bodyweight Shoulder Blaster",
    description: "Upper body workout focused on building strong shoulders without equipment.",
    category: "bodyweight",
    durationMinutes: 15,
    exercises: [
      { name: "Pike Push-Ups", type: "strength", sets: 3, reps: 12, notes: "Pike position, lower head to floor" },
      { name: "Handstand Hold Against Wall", type: "strength", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Build up hold time gradually" },
      { name: "Arm Circles", type: "strength", sets: 3, reps: 20, notes: "Large circles, both directions" },
      { name: "Plank Shoulder Taps", type: "strength", sets: 3, reps: 16, notes: "Minimize hip rotation" },
      { name: "Bear Crawl", type: "cardio", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Move forward and backward" },
    ],
  },
  {
    id: "tpl-010",
    name: "Calf Raise Express",
    description: "Quick lower leg workout to build calf strength and definition.",
    category: "bodyweight",
    durationMinutes: 8,
    exercises: [
      { name: "Standing Calf Raises", type: "strength", sets: 4, reps: 25, notes: "Slow and controlled, full range" },
      { name: "Single-Leg Calf Raises", type: "strength", sets: 3, reps: 15, notes: "Hold onto a wall for balance" },
      { name: "Seated Calf Raises", type: "strength", sets: 3, reps: 20, notes: "Knees bent, press through toes" },
      { name: "Calf Raise Hold", type: "strength", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Hold at the top of the raise" },
    ],
  },
  {
    id: "tpl-011",
    name: "Inchworm Flow",
    description: "Full body mobility exercise that warms up hamstrings, shoulders, and core.",
    category: "bodyweight",
    durationMinutes: 10,
    exercises: [
      { name: "Inchworm Walkouts", type: "flexibility", sets: 3, reps: 8, notes: "Walk hands out to plank, walk back" },
      { name: "Inchworm to Push-Up", type: "strength", sets: 3, reps: 6, notes: "Add a push-up at the bottom" },
      { name: "Inchworm to Side Plank", type: "strength", sets: 3, reps: 6, notes: "Rotate to side plank at the bottom" },
      { name: "Inchworm with Calf Stretch", type: "flexibility", sets: 2, reps: 6, notes: "Pedal feet at the bottom" },
    ],
  },
  {
    id: "tpl-012",
    name: "Pull-Up Progression",
    description: "Back and bicep workout using door-frame pull-up bar variations.",
    category: "bodyweight",
    durationMinutes: 18,
    exercises: [
      { name: "Negative Pull-Ups", type: "strength", sets: 4, reps: 8, notes: "Jump up, lower slowly for 5 seconds" },
      { name: "Australian Pull-Ups", type: "strength", sets: 3, reps: 12, notes: "Under a sturdy table or bar" },
      { name: "Chin-Ups", type: "strength", sets: 3, reps: 8, notes: "Palms facing you" },
      { name: "Hanging Knee Raises", type: "strength", sets: 3, reps: 12, notes: "Engage core, control the swing" },
    ],
  },
  {
    id: "tpl-013",
    name: "Jump Squat Interval",
    description: "Explosive lower body workout combining squats with plyometric jumps.",
    category: "bodyweight",
    durationMinutes: 12,
    exercises: [
      { name: "Jump Squats", type: "cardio", sets: 4, reps: 15, notes: "Land softly, absorb impact" },
      { name: "Tuck Jumps", type: "cardio", sets: 3, reps: 10, notes: "Bring knees to chest mid-air" },
      { name: "Squat to Calf Raise", type: "strength", sets: 3, reps: 15, notes: "Explode up onto toes" },
      { name: "Broad Jumps", type: "cardio", sets: 3, reps: 8, notes: "Jump forward for maximum distance" },
    ],
  },
  {
    id: "tpl-014",
    name: "Plank Variations Circuit",
    description: "Core stability workout using multiple plank positions to challenge your midsection.",
    category: "bodyweight",
    durationMinutes: 15,
    exercises: [
      { name: "Standard Plank", type: "strength", sets: 3, reps: 1, durationMinutes: 1, notes: "Elbows under shoulders, body straight" },
      { name: "Side Plank", type: "strength", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Each side, stack feet or stagger" },
      { name: "Plank with Leg Lift", type: "strength", sets: 3, reps: 12, notes: "Alternate lifting legs" },
      { name: "Plank Jacks", type: "cardio", sets: 3, reps: 20, notes: "Jump feet in and out" },
      { name: "Forearm Plank Hold", type: "strength", sets: 2, reps: 1, durationMinutes: 1.5, notes: "Hold as long as possible" },
    ],
  },
  {
    id: "tpl-015",
    name: "Burpee Breakdown",
    description: "Progressive burpee tutorial workout building from basics to full explosive burpees.",
    category: "bodyweight",
    durationMinutes: 15,
    exercises: [
      { name: "Squat Thrusts", type: "strength", sets: 3, reps: 12, notes: "Step back to plank, no jump" },
      { name: "Half Burpees", type: "strength", sets: 3, reps: 10, notes: "No push-up, add jump at top" },
      { name: "Full Burpees", type: "cardio", sets: 3, reps: 10, notes: "Include push-up and jump" },
      { name: "Burpee Broad Jumps", type: "cardio", sets: 2, reps: 8, notes: "Broad jump instead of vertical" },
    ],
  },
  {
    id: "tpl-016",
    name: "Superman Hold Series",
    description: "Posterior chain strengthening focusing on lower back, glutes, and hamstrings.",
    category: "bodyweight",
    durationMinutes: 10,
    exercises: [
      { name: "Superman Holds", type: "strength", sets: 3, reps: 15, notes: "Lift arms and legs off ground, hold 2 sec" },
      { name: "Alternating Superman", type: "strength", sets: 3, reps: 14, notes: "Opposite arm and leg" },
      { name: "Superman with Pull", type: "strength", sets: 3, reps: 12, notes: "Pull elbows to ribs at the top" },
      { name: "Swimmers", type: "strength", sets: 3, reps: 12, notes: "Flutter arms and legs while lifted" },
    ],
  },
  {
    id: "tpl-017",
    name: "Mountain Climber Blast",
    description: "High-intensity bodyweight cardio and core workout using mountain climber variations.",
    category: "bodyweight",
    durationMinutes: 10,
    exercises: [
      { name: "Standard Mountain Climbers", type: "cardio", sets: 4, reps: 30, notes: "Drive knees to chest quickly" },
      { name: "Cross-Body Mountain Climbers", type: "cardio", sets: 3, reps: 24, notes: "Knee to opposite elbow" },
      { name: "Slow Mountain Climbers", type: "strength", sets: 3, reps: 12, notes: "Control the movement, engage core" },
      { name: "Mountain Climber Sprints", type: "cardio", sets: 3, reps: 20, notes: "Maximum speed for 20 seconds" },
    ],
  },
  {
    id: "tpl-018",
    name: "Hindu Push-Up Flow",
    description: "Dynamic yoga-inspired push-up variation that works the entire upper body.",
    category: "bodyweight",
    durationMinutes: 12,
    exercises: [
      { name: "Hindu Push-Ups", type: "strength", sets: 3, reps: 12, notes: "Swoop down and up in a wave motion" },
      { name: "Dive Bomber Push-Ups", type: "strength", sets: 3, reps: 10, notes: "Reverse the motion on the way back" },
      { name: "Cobra Stretch", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Hold at the top of the push-up" },
      { name: "Down Dog to Plank", type: "strength", sets: 3, reps: 12, notes: "Flow between positions" },
    ],
  },
  {
    id: "tpl-019",
    name: "Pistol Squat Practice",
    description: "Advanced single-leg squat progression for balance and unilateral leg strength.",
    category: "bodyweight",
    durationMinutes: 15,
    exercises: [
      { name: "Assisted Pistol Squats", type: "strength", sets: 3, reps: 8, notes: "Hold onto a doorframe for support" },
      { name: "Box Pistol Squats", type: "strength", sets: 3, reps: 10, notes: "Sit back onto a low box or chair" },
      { name: "Pistol Squat Negatives", type: "strength", sets: 3, reps: 6, notes: "Lower slowly, use both legs to stand" },
      { name: "Shrimp Squats", type: "strength", sets: 2, reps: 8, notes: "Hold back foot behind you" },
    ],
  },
  {
    id: "tpl-020",
    name: "Full Body Bodyweight Blast",
    description: "Comprehensive bodyweight workout hitting every major muscle group in one session.",
    category: "bodyweight",
    durationMinutes: 30,
    exercises: [
      { name: "Push-Ups", type: "strength", sets: 3, reps: 20, notes: "Standard width, full range" },
      { name: "Bodyweight Squats", type: "strength", sets: 3, reps: 25, notes: "Deep squats with good form" },
      { name: "Pull-Ups or Inverted Rows", type: "strength", sets: 3, reps: 10, notes: "Use a bar or sturdy table" },
      { name: "Walking Lunges", type: "strength", sets: 3, reps: 20, notes: "Alternate legs, stay upright" },
      { name: "Plank Hold", type: "strength", sets: 3, reps: 1, durationMinutes: 1, notes: "Maintain rigid body line" },
      { name: "Burpees", type: "cardio", sets: 3, reps: 10, notes: "Full burpee with push-up" },
    ],
  },

  // ==========================================
  // CARDIO (15 templates, tpl-021 to tpl-035)
  // ==========================================
  {
    id: "tpl-021",
    name: "Morning Power Walk",
    description: "Energizing brisk walking routine perfect for starting your day with movement.",
    category: "cardio",
    durationMinutes: 25,
    exercises: [
      { name: "Easy Walk Warm-Up", type: "cardio", sets: 1, reps: 1, durationMinutes: 5, notes: "Light pace to warm up" },
      { name: "Brisk Walking", type: "cardio", sets: 1, reps: 1, durationMinutes: 15, notes: "Fast pace, swing arms" },
      { name: "Cool-Down Walk", type: "cardio", sets: 1, reps: 1, durationMinutes: 5, notes: "Gradually slow your pace" },
    ],
  },
  {
    id: "tpl-022",
    name: "Jogging Interval Builder",
    description: "Alternating jog and walk intervals to build cardiovascular endurance gradually.",
    category: "cardio",
    durationMinutes: 25,
    exercises: [
      { name: "Warm-Up Walk", type: "cardio", sets: 1, reps: 1, durationMinutes: 3, notes: "Easy pace to start" },
      { name: "Jogging Interval", type: "cardio", sets: 8, reps: 1, durationMinutes: 2, notes: "Jog for 2 minutes" },
      { name: "Walking Recovery", type: "cardio", sets: 8, reps: 1, durationMinutes: 1, notes: "Walk for 1 minute between jogs" },
      { name: "Cool-Down Walk", type: "cardio", sets: 1, reps: 1, durationMinutes: 3, notes: "Slow walk to finish" },
    ],
  },
  {
    id: "tpl-023",
    name: "Jumping Jack HIIT",
    description: "High-energy interval workout centered on jumping jacks with active rest periods.",
    category: "cardio",
    durationMinutes: 12,
    exercises: [
      { name: "Jumping Jacks", type: "cardio", sets: 4, reps: 50, notes: "Full range of motion, arms overhead" },
      { name: "High Knees", type: "cardio", sets: 4, reps: 30, notes: "Drive knees to waist height" },
      { name: "Rest", type: "other", sets: 4, reps: 1, durationMinutes: 0.5, notes: "Active recovery, march in place" },
    ],
  },
  {
    id: "tpl-024",
    name: "High Knees Sprint",
    description: "Maximum-effort high knees drill to boost heart rate and burn calories fast.",
    category: "cardio",
    durationMinutes: 10,
    exercises: [
      { name: "Marching in Place", type: "cardio", sets: 1, reps: 1, durationMinutes: 2, notes: "Warm-up at moderate pace" },
      { name: "High Knees", type: "cardio", sets: 5, reps: 1, durationMinutes: 1, notes: "Sprint at maximum effort" },
      { name: "Recovery March", type: "other", sets: 5, reps: 1, durationMinutes: 0.5, notes: "Slow march between sets" },
    ],
  },
  {
    id: "tpl-025",
    name: "Stair Climber Blast",
    description: "Stair climbing workout that builds leg power and cardiovascular fitness.",
    category: "cardio",
    durationMinutes: 20,
    exercises: [
      { name: "Easy Climb Warm-Up", type: "cardio", sets: 1, reps: 1, durationMinutes: 5, notes: "Moderate pace, one step at a time" },
      { name: "Power Climbing", type: "cardio", sets: 3, reps: 1, durationMinutes: 4, notes: "Fast pace, take two steps at a time" },
      { name: "Step-Touch lateral", type: "cardio", sets: 3, reps: 1, durationMinutes: 1, notes: "Step side to side on a single step" },
      { name: "Cool-Down Walk", type: "cardio", sets: 1, reps: 1, durationMinutes: 3, notes: "Easy climb down, catch your breath" },
    ],
  },
  {
    id: "tpl-026",
    name: "Jump Rope Basics",
    description: "Foundational jump rope workout to improve coordination and cardiovascular health.",
    category: "cardio",
    durationMinutes: 15,
    exercises: [
      { name: "Basic Bounce", type: "cardio", sets: 3, reps: 1, durationMinutes: 2, notes: "Two feet together, small jumps" },
      { name: "Alternate Foot Step", type: "cardio", sets: 3, reps: 1, durationMinutes: 2, notes: "Jogging motion with rope" },
      { name: "Rest", type: "other", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Shake out arms and legs" },
      { name: "Double Unders", type: "cardio", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Rope passes twice per jump" },
    ],
  },
  {
    id: "tpl-027",
    name: "Burpee Tabata",
    description: "Intense 4-minute Tabata protocol using burpees for maximum calorie burn.",
    category: "cardio",
    durationMinutes: 8,
    exercises: [
      { name: "Warm-Up Jumping Jacks", type: "cardio", sets: 1, reps: 1, durationMinutes: 2, notes: "Get the heart rate up" },
      { name: "Burpees", type: "cardio", sets: 8, reps: 1, durationMinutes: 0.5, notes: "20 seconds work, 10 seconds rest" },
      { name: "Rest", type: "other", sets: 8, reps: 1, durationMinutes: 0.5, notes: "Complete rest between intervals" },
      { name: "Cool-Down Walk", type: "cardio", sets: 1, reps: 1, durationMinutes: 2, notes: "Slow walking to finish" },
    ],
  },
  {
    id: "tpl-028",
    name: "Outdoor Power Walk",
    description: "Walking workout with hills or inclines for a stronger cardio challenge.",
    category: "cardio",
    durationMinutes: 30,
    exercises: [
      { name: "Flat Walk Warm-Up", type: "cardio", sets: 1, reps: 1, durationMinutes: 5, notes: "Moderate pace on flat ground" },
      { name: "Hill Power Walk", type: "cardio", sets: 4, reps: 1, durationMinutes: 5, notes: "Fast pace uphill, pump arms" },
      { name: "Flat Recovery Walk", type: "cardio", sets: 4, reps: 1, durationMinutes: 1, notes: "Easy pace downhill or flat" },
    ],
  },
  {
    id: "tpl-029",
    name: "Butt Kicks Circuit",
    description: "Dynamic warm-up and cardio routine focused on hamstring activation.",
    category: "cardio",
    durationMinutes: 10,
    exercises: [
      { name: "Butt Kicks", type: "cardio", sets: 4, reps: 30, notes: "Heel to glute, keep knees down" },
      { name: "High Knees", type: "cardio", sets: 4, reps: 30, notes: "Alternate with butt kicks" },
      { name: "Rest", type: "other", sets: 4, reps: 1, durationMinutes: 0.5, notes: "Light march in place" },
    ],
  },
  {
    id: "tpl-030",
    name: "Shadow Boxing Cardio",
    description: "Engaging cardio workout using boxing movements to burn calories and relieve stress.",
    category: "cardio",
    durationMinutes: 15,
    exercises: [
      { name: "Jump Rope Warm-Up", type: "cardio", sets: 1, reps: 1, durationMinutes: 3, notes: "Light bouncing" },
      { name: "Jab-Cross Combo", type: "cardio", sets: 4, reps: 1, durationMinutes: 1, notes: "Alternate punches, rotate hips" },
      { name: "Uppercut Flurry", type: "cardio", sets: 4, reps: 1, durationMinutes: 1, notes: "Fast uppercuts, stay on toes" },
      { name: "Defensive Slips", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Slip left and right, core engaged" },
    ],
  },
  {
    id: "tpl-031",
    name: "Sprint Interval Training",
    description: "Outdoor or treadmill sprint intervals for serious cardiovascular conditioning.",
    category: "cardio",
    durationMinutes: 20,
    exercises: [
      { name: "Jog Warm-Up", type: "cardio", sets: 1, reps: 1, durationMinutes: 5, notes: "Easy jog to warm up" },
      { name: "Sprints", type: "cardio", sets: 6, reps: 1, durationMinutes: 0.5, notes: "Maximum effort for 30 seconds" },
      { name: "Walking Recovery", type: "other", sets: 6, reps: 1, durationMinutes: 2, notes: "Walk between sprints" },
    ],
  },
  {
    id: "tpl-032",
    name: "Dance Cardio Fun",
    description: "Enjoyable dance-based cardio that improves coordination while burning calories.",
    category: "cardio",
    durationMinutes: 20,
    exercises: [
      { name: "March in Place", type: "cardio", sets: 1, reps: 1, durationMinutes: 3, notes: "Rhythmic marching to music" },
      { name: "Step Touch Side to Side", type: "cardio", sets: 1, reps: 1, durationMinutes: 5, notes: "Step and tap, add arm movements" },
      { name: "Grapevine", type: "cardio", sets: 1, reps: 1, durationMinutes: 5, notes: "Cross step with a tap" },
      { name: "V-Step", type: "cardio", sets: 1, reps: 1, durationMinutes: 5, notes: "Step wide, then back to center" },
      { name: "Cool-Down Stretch", type: "flexibility", sets: 1, reps: 1, durationMinutes: 2, notes: "Gentle full body stretch" },
    ],
  },
  {
    id: "tpl-033",
    name: "Jump Rope HIIT",
    description: "Intense jump rope interval workout combining skill and cardiovascular endurance.",
    category: "cardio",
    durationMinutes: 15,
    exercises: [
      { name: "Basic Bounce", type: "cardio", sets: 1, reps: 1, durationMinutes: 3, notes: "Warm up with simple jumps" },
      { name: "Speed Steps", type: "cardio", sets: 6, reps: 1, durationMinutes: 1, notes: "Fast alternate foot jumps" },
      { name: "Rest", type: "other", sets: 6, reps: 1, durationMinutes: 0.5, notes: "Stop and catch breath" },
      { name: "Criss-Cross", type: "cardio", sets: 3, reps: 1, durationMinutes: 1, notes: "Cross arms in front" },
      { name: "Cool-Down Walk", type: "cardio", sets: 1, reps: 1, durationMinutes: 2, notes: "Slow walking to finish" },
    ],
  },
  {
    id: "tpl-034",
    name: "Lateral Shuffle Drill",
    description: "Side-to-side agility workout that improves lateral movement and coordination.",
    category: "cardio",
    durationMinutes: 12,
    exercises: [
      { name: "Side Shuffles", type: "cardio", sets: 4, reps: 1, durationMinutes: 1, notes: "Shuffle 10 yards and back" },
      { name: "Carioca Drill", type: "cardio", sets: 4, reps: 1, durationMinutes: 1, notes: "Cross feet over and behind" },
      { name: "Lateral High Knees", type: "cardio", sets: 3, reps: 1, durationMinutes: 1, notes: "High knees moving sideways" },
      { name: "Rest", type: "other", sets: 4, reps: 1, durationMinutes: 0.5, notes: "Light march in place" },
    ],
  },
  {
    id: "tpl-035",
    name: "Power Walking with Arm Work",
    description: "Walking cardio enhanced with overhead arm movements for a total body burn.",
    category: "cardio",
    durationMinutes: 20,
    exercises: [
      { name: "Brisk Walk", type: "cardio", sets: 1, reps: 1, durationMinutes: 10, notes: "Fast pace, strong arm swings" },
      { name: "Overhead Arm Press While Walking", type: "cardio", sets: 3, reps: 1, durationMinutes: 2, notes: "Press arms up overhead while walking" },
      { name: "Bicep Curl Motion", type: "cardio", sets: 3, reps: 1, durationMinutes: 1, notes: "Pump arms in curling motion" },
      { name: "Cool-Down Walk", type: "cardio", sets: 1, reps: 1, durationMinutes: 2, notes: "Easy pace to finish" },
    ],
  },

  // ==========================================
  // STRETCHING (15 templates, tpl-036 to tpl-050)
  // ==========================================
  {
    id: "tpl-036",
    name: "Full Body Stretch",
    description: "Complete stretching routine targeting all major muscle groups for improved flexibility.",
    category: "stretching",
    durationMinutes: 15,
    exercises: [
      { name: "Neck Rolls", type: "flexibility", sets: 1, reps: 10, notes: "Slow, controlled circles both ways" },
      { name: "Shoulder Shrugs", type: "flexibility", sets: 1, reps: 15, notes: "Lift shoulders to ears, hold, release" },
      { name: "Standing Hamstring Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each leg, keep back straight" },
      { name: "Quad Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Pull heel to glute, knees together" },
      { name: "Chest Opener", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Clasp hands behind back, lift" },
      { name: "Child's Pose", type: "flexibility", sets: 1, reps: 1, durationMinutes: 1, notes: "Sit back on heels, arms extended" },
    ],
  },
  {
    id: "tpl-037",
    name: "Hamstring Focus Stretch",
    description: "Targeted stretching routine to loosen tight hamstrings and lower back.",
    category: "stretching",
    durationMinutes: 10,
    exercises: [
      { name: "Seated Forward Fold", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Reach for toes, keep legs straight" },
      { name: "Standing Toe Touch", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Slight bend in knees if needed" },
      { name: "Supine Hamstring Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Lie on back, pull leg toward you" },
      { name: "Pigeon Pose", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, sink hips forward" },
    ],
  },
  {
    id: "tpl-038",
    name: "Hip Opener Flow",
    description: "Deep hip stretching sequence to relieve tension from prolonged sitting.",
    category: "stretching",
    durationMinutes: 12,
    exercises: [
      { name: "Butterfly Stretch", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Soles together, press knees down" },
      { name: "90/90 Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, front and back leg bent" },
      { name: "Frog Stretch", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Wide knees, push hips back" },
      { name: "Hip Flexor Lunge Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, push hips forward" },
    ],
  },
  {
    id: "tpl-039",
    name: "Shoulder and Neck Relief",
    description: "Targeted stretching for upper body tension from desk work and poor posture.",
    category: "stretching",
    durationMinutes: 8,
    exercises: [
      { name: "Cross-Body Shoulder Stretch", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Each arm, pull across chest" },
      { name: "Tricep Overhead Stretch", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Each arm, reach down back" },
      { name: "Neck Side Stretch", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Each side, gently pull head" },
      { name: "Chin Tucks", type: "flexibility", sets: 2, reps: 15, notes: "Draw chin back to create double chin" },
      { name: "Chest Doorway Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Arm on doorframe, lean forward" },
    ],
  },
  {
    id: "tpl-040",
    name: "Morning Wake-Up Stretch",
    description: "Gentle full body stretching routine designed to ease into your morning.",
    category: "stretching",
    durationMinutes: 10,
    exercises: [
      { name: "Cat-Cow Stretch", type: "flexibility", sets: 2, reps: 10, notes: "Arch and round spine on all fours" },
      { name: "Seated Spinal Twist", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, sit tall and rotate" },
      { name: "Standing Side Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, reach overhead and lean" },
      { name: "Ankle Circles", type: "flexibility", sets: 2, reps: 10, notes: "Both directions, both ankles" },
      { name: "Wrist Circles", type: "flexibility", sets: 2, reps: 10, notes: "Both directions" },
    ],
  },
  {
    id: "tpl-041",
    name: "Pre-Sleep Relaxation Stretch",
    description: "Calming stretching sequence to release tension before bedtime.",
    category: "stretching",
    durationMinutes: 10,
    exercises: [
      { name: "Legs Up the Wall", type: "flexibility", sets: 1, reps: 1, durationMinutes: 2, notes: "Lie on back, legs against wall" },
      { name: "Supine Spinal Twist", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, knees fall to one side" },
      { name: "Happy Baby Pose", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Grab feet, pull knees to armpits" },
      { name: "Neck Stretches", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Gentle tilts and turns" },
    ],
  },
  {
    id: "tpl-042",
    name: "Runner's Stretch Routine",
    description: "Essential stretching routine for runners targeting calves, hamstrings, and hip flexors.",
    category: "stretching",
    durationMinutes: 12,
    exercises: [
      { name: "Standing Calf Stretch", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Each leg, wall for support" },
      { name: "Half-Kneeling Hip Flexor Stretch", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Each side, push hips forward" },
      { name: "Standing Quad Stretch", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Hold foot, knees together" },
      { name: "Figure Four Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Lie on back, cross ankle over knee" },
    ],
  },
  {
    id: "tpl-043",
    name: "Desk Worker Relief",
    description: "Quick stretching routine designed to counteract hours of sitting at a desk.",
    category: "stretching",
    durationMinutes: 8,
    exercises: [
      { name: "Seated Spinal Twist", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, in your chair" },
      { name: "Neck Rolls", type: "flexibility", sets: 2, reps: 8, notes: "Slow circles both directions" },
      { name: "Chest Opener Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Clasp hands behind back" },
      { name: "Wrist Flexor Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Extend arm, pull fingers back" },
    ],
  },
  {
    id: "tpl-044",
    name: "Spine Mobility Flow",
    description: "Gentle spinal articulation exercises to improve back flexibility and reduce stiffness.",
    category: "stretching",
    durationMinutes: 10,
    exercises: [
      { name: "Cat-Cow Flow", type: "flexibility", sets: 3, reps: 10, notes: "Slow, breathe with each movement" },
      { name: "Seated Spinal Rotation", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, hold the twist" },
      { name: "Thread the Needle", type: "flexibility", sets: 2, reps: 8, notes: "Reach one arm under the other" },
      { name: "Sphinx Pose", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Lie face down, prop on forearms" },
    ],
  },
  {
    id: "tpl-045",
    name: "Hip and Lower Back Release",
    description: "Deep stretching sequence targeting chronic hip tightness and lower back tension.",
    category: "stretching",
    durationMinutes: 12,
    exercises: [
      { name: "Child's Pose", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Wide knees for deeper hip stretch" },
      { name: "Lizard Pose", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, lower onto forearms" },
      { name: "Supine Figure Four", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, pull legs toward you" },
      { name: "Knee to Chest Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Hug each knee individually" },
    ],
  },
  {
    id: "tpl-046",
    name: "Full Body Morning Stretch",
    description: "Comprehensive morning stretching routine to energize your entire body.",
    category: "stretching",
    durationMinutes: 15,
    exercises: [
      { name: "Full Body Reach", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Lie flat, reach arms overhead" },
      { name: "Rolling to Sit", type: "flexibility", sets: 3, reps: 5, notes: "Rock up to seated position" },
      { name: "Seated Forward Fold", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Reach for toes" },
      { name: "Butterfly Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Press knees toward floor" },
      { name: "Standing Forward Fold", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Let head hang heavy" },
    ],
  },
  {
    id: "tpl-047",
    name: "Arm and Shoulder Mobility",
    description: "Mobility work for shoulders, elbows, and wrists to improve range of motion.",
    category: "stretching",
    durationMinutes: 8,
    exercises: [
      { name: "Arm Circles", type: "flexibility", sets: 3, reps: 15, notes: "Small to large, both directions" },
      { name: "Wall Angels", type: "flexibility", sets: 3, reps: 10, notes: "Back against wall, slide arms" },
      { name: "Prayer Stretch", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Press palms together, elbows out" },
      { name: "Finger Interlace Stretch", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Turn palms outward and stretch" },
    ],
  },
  {
    id: "tpl-048",
    name: "Ankle and Foot Mobility",
    description: "Targeted stretching for feet and ankles to prevent injury and improve balance.",
    category: "stretching",
    durationMinutes: 7,
    exercises: [
      { name: "Ankle Circles", type: "flexibility", sets: 3, reps: 10, notes: "Both directions, each foot" },
      { name: "Calf Stretch on Wall", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Straight and bent knee versions" },
      { name: "Toe Yoga", type: "flexibility", sets: 2, reps: 10, notes: "Lift big toe, then small toes" },
      { name: "Plantar Fascia Roll", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Roll a ball underfoot" },
    ],
  },
  {
    id: "tpl-049",
    name: "Chest and Upper Back Stretch",
    description: "Opening stretch for the anterior and posterior upper body to improve posture.",
    category: "stretching",
    durationMinutes: 8,
    exercises: [
      { name: "Doorway Chest Stretch", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Arm at 90 degrees on doorframe" },
      { name: "Rounded Back Stretch", type: "flexibility", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Clasp hands in front, round back" },
      { name: "Cow Face Arms", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, reach behind back" },
      { name: "Scapular Protraction", type: "flexibility", sets: 2, reps: 15, notes: "Push forward, spread shoulder blades" },
    ],
  },
  {
    id: "tpl-050",
    name: "Evening Wind-Down Stretch",
    description: "Relaxing stretching routine perfect for unwinding after a long day of job hunting.",
    category: "stretching",
    durationMinutes: 10,
    exercises: [
      { name: "Child's Pose", type: "flexibility", sets: 1, reps: 1, durationMinutes: 1, notes: "Rest forehead on ground" },
      { name: "Supine Twist", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, let gravity do the work" },
      { name: "Legs on Chair", type: "flexibility", sets: 1, reps: 1, durationMinutes: 2, notes: "Rest legs on seat of chair" },
      { name: "Neck Release", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Gentle weight of hand on head" },
    ],
  },

  // ==========================================
  // STRENGTH (15 templates, tpl-051 to tpl-065)
  // ==========================================
  {
    id: "tpl-051",
    name: "Dumbbell Upper Body",
    description: "Upper body strength workout using dumbbells — requires dumbbells (5-25 lbs).",
    category: "strength",
    durationMinutes: 30,
    exercises: [
      { name: "Dumbbell Bench Press", type: "strength", sets: 4, reps: 10, notes: "Lie on floor or bench, press up" },
      { name: "Dumbbell Rows", type: "strength", sets: 4, reps: 12, notes: "One arm at a time, pull to hip" },
      { name: "Shoulder Press", type: "strength", sets: 3, reps: 10, notes: "Seated or standing, press overhead" },
      { name: "Bicep Curls", type: "strength", sets: 3, reps: 12, notes: "Alternate arms, full range" },
      { name: "Tricep Kickbacks", type: "strength", sets: 3, reps: 12, notes: "Hinge forward, extend arm back" },
    ],
  },
  {
    id: "tpl-052",
    name: "Resistance Band Full Body",
    description: "Total body strength training using resistance bands — requires a set of bands.",
    category: "strength",
    durationMinutes: 35,
    exercises: [
      { name: "Band Squats", type: "strength", sets: 4, reps: 15, notes: "Stand on band, hold handles at shoulders" },
      { name: "Band Chest Press", type: "strength", sets: 3, reps: 12, notes: "Band behind back, press forward" },
      { name: "Band Rows", type: "strength", sets: 3, reps: 15, notes: "Anchor band, pull toward torso" },
      { name: "Band Lateral Raises", type: "strength", sets: 3, reps: 12, notes: "Stand on band, raise arms sideways" },
      { name: "Band Deadlift", type: "strength", sets: 3, reps: 12, notes: "Stand on band, hinge at hips" },
      { name: "Band Bicep Curls", type: "strength", sets: 3, reps: 15, notes: "Stand on band, curl handles" },
    ],
  },
  {
    id: "tpl-053",
    name: "Dumbbell Leg Day",
    description: "Lower body strength session using dumbbells — requires dumbbells (10-30 lbs).",
    category: "strength",
    durationMinutes: 35,
    exercises: [
      { name: "Dumbbell Goblet Squats", type: "strength", sets: 4, reps: 12, notes: "Hold one dumbbell at chest" },
      { name: "Dumbbell Lunges", type: "strength", sets: 4, reps: 12, notes: "Hold dumbbells at sides" },
      { name: "Dumbbell Romanian Deadlift", type: "strength", sets: 4, reps: 10, notes: "Hinge at hips, slight knee bend" },
      { name: "Dumbbell Calf Raises", type: "strength", sets: 3, reps: 20, notes: "Hold dumbbells, raise onto toes" },
      { name: "Dumbbell Step-Ups", type: "strength", sets: 3, reps: 10, notes: "Hold dumbbells, step onto bench" },
    ],
  },
  {
    id: "tpl-054",
    name: "Kettlebell Swing Circuit",
    description: "Explosive kettlebell workout for power and cardiovascular conditioning — requires a kettlebell.",
    category: "strength",
    durationMinutes: 25,
    exercises: [
      { name: "Kettlebell Swings", type: "strength", sets: 4, reps: 20, notes: "Hip hinge, explosive thrust" },
      { name: "Goblet Squats", type: "strength", sets: 3, reps: 15, notes: "Hold kettlebell at chest" },
      { name: "Single-Arm Clean", type: "strength", sets: 3, reps: 10, notes: "Each arm, explosive pull" },
      { name: "Turkish Get-Up", type: "strength", sets: 2, reps: 5, notes: "Each side, controlled movement" },
    ],
  },
  {
    id: "tpl-055",
    name: "Dumbbell Push-Pull Split",
    description: "Balanced upper body session alternating push and pull movements — requires dumbbells.",
    category: "strength",
    durationMinutes: 40,
    exercises: [
      { name: "Incline Dumbbell Press", type: "strength", sets: 4, reps: 10, notes: "Prop upper body at angle" },
      { name: "Bent-Over Rows", type: "strength", sets: 4, reps: 12, notes: "Both arms, squeeze shoulder blades" },
      { name: "Lateral Raises", type: "strength", sets: 3, reps: 12, notes: "Raise to shoulder height" },
      { name: "Face Pulls with Band", type: "strength", sets: 3, reps: 15, notes: "Pull band toward face" },
      { name: "Overhead Tricep Extension", type: "strength", sets: 3, reps: 12, notes: "One dumbbell behind head" },
      { name: "Hammer Curls", type: "strength", sets: 3, reps: 12, notes: "Palms face each other" },
    ],
  },
  {
    id: "tpl-056",
    name: "Resistance Band Upper Body",
    description: "Upper body focused resistance band workout — requires medium and heavy bands.",
    category: "strength",
    durationMinutes: 25,
    exercises: [
      { name: "Band Pull-Aparts", type: "strength", sets: 4, reps: 20, notes: "Hold band at arm's length, pull apart" },
      { name: "Band Chest Fly", type: "strength", sets: 3, reps: 15, notes: "Band behind back, arms wide" },
      { name: "Band Shoulder Press", type: "strength", sets: 3, reps: 12, notes: "Stand on band, press overhead" },
      { name: "Band Tricep Pushdown", type: "strength", sets: 3, reps: 15, notes: "Anchor high, push down" },
      { name: "Band Bicep Curls", type: "strength", sets: 3, reps: 15, notes: "Stand on band, curl" },
    ],
  },
  {
    id: "tpl-057",
    name: "Dumbbell Core and Arms",
    description: "Targeted dumbbell workout for arm hypertrophy and core stability — requires dumbbells.",
    category: "strength",
    durationMinutes: 30,
    exercises: [
      { name: "Dumbbell Curl to Press", type: "strength", sets: 3, reps: 10, notes: "Curl up, then press overhead" },
      { name: "Concentration Curls", type: "strength", sets: 3, reps: 12, notes: "Each arm, elbow on inner thigh" },
      { name: "Dumbbell Skull Crushers", type: "strength", sets: 3, reps: 12, notes: "Lower to forehead, extend up" },
      { name: "Russian Twists with Dumbbell", type: "strength", sets: 3, reps: 20, notes: "Hold dumbbell, rotate torso" },
      { name: "Dumbbell Side Bend", type: "strength", sets: 3, reps: 15, notes: "Each side, hold dumbbell at side" },
    ],
  },
  {
    id: "tpl-058",
    name: "Resistance Band Legs",
    description: "Lower body resistance band workout for glutes and thighs — requires a heavy loop band.",
    category: "strength",
    durationMinutes: 25,
    exercises: [
      { name: "Banded Squats", type: "strength", sets: 4, reps: 20, notes: "Band above knees, squat deep" },
      { name: "Banded Lateral Walks", type: "strength", sets: 3, reps: 15, notes: "Band above knees, step sideways" },
      { name: "Banded Glute Bridges", type: "strength", sets: 4, reps: 20, notes: "Band above knees, squeeze at top" },
      { name: "Banded Clamshells", type: "strength", sets: 3, reps: 20, notes: "Lie on side, open knees" },
      { name: "Banded Donkey Kicks", type: "strength", sets: 3, reps: 15, notes: "Each leg, kick back against band" },
    ],
  },
  {
    id: "tpl-059",
    name: "Dumbbell Total Body",
    description: "Full body dumbbell routine hitting all major muscle groups — requires dumbbells (5-20 lbs).",
    category: "strength",
    durationMinutes: 45,
    exercises: [
      { name: "Dumbbell Thrusters", type: "strength", sets: 4, reps: 12, notes: "Squat, then press overhead" },
      { name: "Dumbbell Bent-Over Row", type: "strength", sets: 4, reps: 12, notes: "Hinge forward, row to hip" },
      { name: "Dumbbell Reverse Lunge", type: "strength", sets: 3, reps: 12, notes: "Each leg, hold at sides" },
      { name: "Dumbbell Floor Press", type: "strength", sets: 3, reps: 12, notes: "Lie on floor, press up" },
      { name: "Dumbbell Renegade Row", type: "strength", sets: 3, reps: 10, notes: "Plank position, row one arm" },
      { name: "Dumbbell Shrugs", type: "strength", sets: 3, reps: 15, notes: "Hold at sides, shrug shoulders" },
    ],
  },
  {
    id: "tpl-060",
    name: "Resistance Band Shoulders",
    description: "Isolated shoulder strengthening using bands for safe and effective training — requires bands.",
    category: "strength",
    durationMinutes: 20,
    exercises: [
      { name: "Band Overhead Press", type: "strength", sets: 4, reps: 12, notes: "Stand on band, press overhead" },
      { name: "Band Lateral Raise", type: "strength", sets: 3, reps: 15, notes: "Stand on band, raise sideways" },
      { name: "Band Front Raise", type: "strength", sets: 3, reps: 12, notes: "Stand on band, raise forward" },
      { name: "Band Face Pull", type: "strength", sets: 3, reps: 15, notes: "Anchor at face height, pull back" },
      { name: "Band External Rotation", type: "strength", sets: 3, reps: 15, notes: "Elbow at side, rotate outward" },
    ],
  },
  {
    id: "tpl-061",
    name: "Dumbbell Back and Biceps",
    description: "Focused pulling workout with dumbbells for a wider back — requires dumbbells.",
    category: "strength",
    durationMinutes: 30,
    exercises: [
      { name: "Dumbbell Deadlift", type: "strength", sets: 4, reps: 10, notes: "Hold at sides, hinge at hips" },
      { name: "Single-Arm Dumbbell Row", type: "strength", sets: 4, reps: 12, notes: "Each arm, pull to hip" },
      { name: "Dumbbell Pullover", type: "strength", sets: 3, reps: 12, notes: "Lie on floor, lower behind head" },
      { name: "Dumbbell Shrugs", type: "strength", sets: 3, reps: 15, notes: "Hold at sides, shrug up" },
      { name: "Incline Dumbbell Curl", type: "strength", sets: 3, reps: 10, notes: "Lean back on incline bench" },
    ],
  },
  {
    id: "tpl-062",
    name: "Resistance Band Chest and Triceps",
    description: "Push-focused band workout for chest and arms — requires a medium resistance band.",
    category: "strength",
    durationMinutes: 25,
    exercises: [
      { name: "Band Chest Press", type: "strength", sets: 4, reps: 15, notes: "Band behind back, press forward" },
      { name: "Band Push-Up", type: "strength", sets: 3, reps: 12, notes: "Band across back, hold in hands" },
      { name: "Band Fly", type: "strength", sets: 3, reps: 15, notes: "Arms wide, squeeze at center" },
      { name: "Band Tricep Extension", type: "strength", sets: 3, reps: 15, notes: "Anchor high, extend down" },
      { name: "Band Push-Apart", type: "strength", sets: 3, reps: 20, notes: "Hold at chest height, pull apart" },
    ],
  },
  {
    id: "tpl-063",
    name: "Dumbbell Shoulder Sculpt",
    description: "Complete shoulder workout with dumbbells for balanced development — requires dumbbells.",
    category: "strength",
    durationMinutes: 30,
    exercises: [
      { name: "Dumbbell Overhead Press", type: "strength", sets: 4, reps: 10, notes: "Seated or standing, full range" },
      { name: "Dumbbell Lateral Raise", type: "strength", sets: 4, reps: 12, notes: "Raise to shoulder height" },
      { name: "Dumbbell Front Raise", type: "strength", sets: 3, reps: 12, notes: "Alternate arms, to eye level" },
      { name: "Dumbbell Rear Delt Fly", type: "strength", sets: 3, reps: 15, notes: "Bent over, raise arms out" },
      { name: "Dumbbell Upright Row", type: "strength", sets: 3, reps: 12, notes: "Pull to chin, elbows high" },
    ],
  },
  {
    id: "tpl-064",
    name: "Resistance Band Glute Blast",
    description: "Intense glute-focused resistance band workout — requires heavy loop band.",
    category: "strength",
    durationMinutes: 20,
    exercises: [
      { name: "Banded Hip Thrusts", type: "strength", sets: 4, reps: 20, notes: "Shoulders on bench, band above knees" },
      { name: "Banded Fire Hydrants", type: "strength", sets: 3, reps: 15, notes: "All fours, lift leg to side" },
      { name: "Banded Standing Kickbacks", type: "strength", sets: 3, reps: 15, notes: "Each leg, kick back against band" },
      { name: "Banded Squat Walk", type: "strength", sets: 3, reps: 12, notes: "Stay low, step forward" },
    ],
  },
  {
    id: "tpl-065",
    name: "Dumbbell Compound Circuit",
    description: "Multi-joint dumbbell movements for maximum strength gains — requires dumbbells (10-25 lbs).",
    category: "strength",
    durationMinutes: 40,
    exercises: [
      { name: "Dumbbell Clean and Press", type: "strength", sets: 4, reps: 8, notes: "Explosive pull from floor to overhead" },
      { name: "Dumbbell Front Squat", type: "strength", sets: 4, reps: 10, notes: "Hold at shoulders, squat deep" },
      { name: "Dumbbell Bent-Over Row", type: "strength", sets: 4, reps: 10, notes: "Hinge forward, row both arms" },
      { name: "Dumbbell Reverse Lunge to Curl", type: "strength", sets: 3, reps: 10, notes: "Lunge back, then curl at top" },
      { name: "Dumbbell Renegade Row to Push-Up", type: "strength", sets: 3, reps: 8, notes: "Row each arm, then push-up" },
    ],
  },

  // ==========================================
  // YOGA (10 templates, tpl-066 to tpl-075)
  // ==========================================
  {
    id: "tpl-066",
    name: "Sun Salutation A",
    description: "Classic yoga sun salutation sequence for a full body energizing flow.",
    category: "yoga",
    durationMinutes: 10,
    exercises: [
      { name: "Mountain Pose", type: "flexibility", sets: 1, reps: 1, durationMinutes: 0.5, notes: "Stand tall, palms together" },
      { name: "Upward Salute", type: "flexibility", sets: 1, reps: 1, durationMinutes: 0.5, notes: "Arms overhead, slight backbend" },
      { name: "Forward Fold", type: "flexibility", sets: 5, reps: 1, durationMinutes: 0.5, notes: "Fold from hips, hands to floor" },
      { name: "Halfway Lift", type: "flexibility", sets: 5, reps: 1, durationMinutes: 0.5, notes: "Flat back, hands on shins" },
      { name: "Plank to Chaturanga", type: "strength", sets: 5, reps: 1, durationMinutes: 0.5, notes: "Lower halfway down" },
      { name: "Upward-Facing Dog", type: "flexibility", sets: 5, reps: 1, durationMinutes: 0.5, notes: "Chest forward, thighs off ground" },
      { name: "Downward-Facing Dog", type: "flexibility", sets: 5, reps: 1, durationMinutes: 1, notes: "Hold for 5 breaths, heels down" },
    ],
  },
  {
    id: "tpl-067",
    name: "Beginner Yoga Flow",
    description: "Gentle yoga sequence perfect for those new to yoga practice.",
    category: "yoga",
    durationMinutes: 15,
    exercises: [
      { name: "Child's Pose", type: "flexibility", sets: 1, reps: 1, durationMinutes: 1, notes: "Rest and center yourself" },
      { name: "Tabletop Position", type: "flexibility", sets: 1, reps: 1, durationMinutes: 0.5, notes: "All fours, wrists under shoulders" },
      { name: "Cat-Cow", type: "flexibility", sets: 2, reps: 10, notes: "Arch and round spine with breath" },
      { name: "Downward-Facing Dog", type: "flexibility", sets: 3, reps: 1, durationMinutes: 1, notes: "Pedal out your feet" },
      { name: "Warrior I", type: "strength", sets: 2, reps: 1, durationMinutes: 1, notes: "Each side, front knee over ankle" },
      { name: "Warrior II", type: "strength", sets: 2, reps: 1, durationMinutes: 1, notes: "Each side, gaze over front hand" },
      { name: "Seated Forward Fold", type: "flexibility", sets: 1, reps: 1, durationMinutes: 1, notes: "Reach for your toes" },
      { name: "Corpse Pose", type: "flexibility", sets: 1, reps: 1, durationMinutes: 2, notes: "Lie flat, relax completely" },
    ],
  },
  {
    id: "tpl-068",
    name: "5-Minute Morning Yoga",
    description: "Quick morning yoga routine to wake up your body and mind before the day.",
    category: "yoga",
    durationMinutes: 5,
    exercises: [
      { name: "Mountain Pose with Arms Up", type: "flexibility", sets: 1, reps: 1, durationMinutes: 0.5, notes: "Deep inhale, arms sweep up" },
      { name: "Standing Forward Fold", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Exhale, fold from hips" },
      { name: "Low Lunge", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, sink hips forward" },
      { name: "Downward Dog", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Press heels toward floor" },
    ],
  },
  {
    id: "tpl-069",
    name: "Power Yoga Flow",
    description: "Dynamic yoga sequence that builds heat, strength, and flexibility.",
    category: "yoga",
    durationMinutes: 20,
    exercises: [
      { name: "Sun Salutation B", type: "strength", sets: 3, reps: 1, durationMinutes: 2, notes: "Chair pose to warrior to chaturanga" },
      { name: "Warrior III", type: "strength", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, body parallel to floor" },
      { name: "Extended Side Angle", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, arm overhead" },
      { name: "Triangle Pose", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, reach for shin" },
      { name: "Half Moon Pose", type: "strength", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, balance on one leg" },
      { name: "Seated Twist", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, lengthen spine" },
    ],
  },
  {
    id: "tpl-070",
    name: "10-Minute Yoga Reset",
    description: "Quick yoga break to reset your posture and reduce tension during the workday.",
    category: "yoga",
    durationMinutes: 10,
    exercises: [
      { name: "Neck Stretches", type: "flexibility", sets: 1, reps: 1, durationMinutes: 1, notes: "Gentle tilts and turns" },
      { name: "Seated Cat-Cow", type: "flexibility", sets: 2, reps: 10, notes: "Hands on knees, arch and round" },
      { name: "Thread the Needle", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, shoulder to ground" },
      { name: "Seated Forward Fold", type: "flexibility", sets: 1, reps: 1, durationMinutes: 1, notes: "Reach forward gently" },
      { name: "Supine Twist", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, knees to one side" },
    ],
  },
  {
    id: "tpl-071",
    name: "Yoga for Flexibility",
    description: "Deep stretching yoga sequence to improve overall flexibility and range of motion.",
    category: "yoga",
    durationMinutes: 20,
    exercises: [
      { name: "Low Lunge", type: "flexibility", sets: 2, reps: 1, durationMinutes: 1, notes: "Each side, back knee down" },
      { name: "Lizard Pose", type: "flexibility", sets: 2, reps: 1, durationMinutes: 1, notes: "Each side, forearms to floor" },
      { name: "Pigeon Pose", type: "flexibility", sets: 2, reps: 1, durationMinutes: 1, notes: "Each side, fold forward" },
      { name: "Seated Wide-Legged Fold", type: "flexibility", sets: 2, reps: 1, durationMinutes: 1, notes: "Walk hands forward" },
      { name: "Supine Hamstring Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 1, notes: "Each leg, use a strap if needed" },
      { name: "Happy Baby", type: "flexibility", sets: 2, reps: 1, durationMinutes: 1, notes: "Rock gently side to side" },
    ],
  },
  {
    id: "tpl-072",
    name: "Bedtime Yoga Routine",
    description: "Calming yoga poses to release tension and prepare for restful sleep.",
    category: "yoga",
    durationMinutes: 10,
    exercises: [
      { name: "Child's Pose", type: "flexibility", sets: 1, reps: 1, durationMinutes: 1, notes: "Wide knees, arms extended" },
      { name: "Reclined Butterfly", type: "flexibility", sets: 1, reps: 1, durationMinutes: 2, notes: "Soles together, let knees fall" },
      { name: "Supine Spinal Twist", type: "flexibility", sets: 2, reps: 1, durationMinutes: 1, notes: "Each side, knees to one side" },
      { name: "Legs Up the Wall", type: "flexibility", sets: 1, reps: 1, durationMinutes: 3, notes: "Deep breathing, complete relaxation" },
    ],
  },
  {
    id: "tpl-073",
    name: "Warrior Flow",
    description: "Yoga sequence flowing through warrior poses for strength and stability.",
    category: "yoga",
    durationMinutes: 15,
    exercises: [
      { name: "Warrior I", type: "strength", sets: 2, reps: 1, durationMinutes: 1, notes: "Each side, arms overhead" },
      { name: "Warrior II", type: "strength", sets: 2, reps: 1, durationMinutes: 1, notes: "Each side, strong stance" },
      { name: "Reverse Warrior", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, reach back" },
      { name: "Extended Side Angle", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, forearm to thigh" },
      { name: "Humble Warrior", type: "strength", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, bow forward" },
      { name: "Peaceful Warrior", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, open chest" },
    ],
  },
  {
    id: "tpl-074",
    name: "Core Yoga Flow",
    description: "Yoga-based core strengthening sequence combining balance and stability.",
    category: "yoga",
    durationMinutes: 15,
    exercises: [
      { name: "Plank Pose", type: "strength", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Hold strong body line" },
      { name: "Boat Pose", type: "strength", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Balance on sit bones, legs up" },
      { name: "Side Plank", type: "strength", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, stack feet" },
      { name: "Forearm Plank", type: "strength", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Elbows under shoulders" },
      { name: "Revolved Triangle", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, twist from core" },
    ],
  },
  {
    id: "tpl-075",
    name: "Chair Yoga for Desk Workers",
    description: "Seated and standing yoga poses you can do at your desk without changing clothes.",
    category: "yoga",
    durationMinutes: 8,
    exercises: [
      { name: "Seated Mountain Pose", type: "flexibility", sets: 1, reps: 1, durationMinutes: 0.5, notes: "Sit tall, feet flat on floor" },
      { name: "Seated Twist", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, lengthen spine" },
      { name: "Seated Cat-Cow", type: "flexibility", sets: 2, reps: 10, notes: "Hands on knees, breathe deeply" },
      { name: "Standing Forward Fold", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Slight knee bend, let head hang" },
      { name: "Eagle Arms", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Wrap arms, lift elbows" },
      { name: "Standing Figure Four", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Ankle on knee, sit back" },
    ],
  },

  // ==========================================
  // DESK_BREAK (10 templates, tpl-076 to tpl-085)
  // ==========================================
  {
    id: "tpl-076",
    name: "2-Minute Desk Reset",
    description: "Ultra-quick micro-routine to refresh between job applications.",
    category: "desk_break",
    durationMinutes: 2,
    exercises: [
      { name: "Neck Rolls", type: "flexibility", sets: 1, reps: 5, notes: "Slow circles both directions" },
      { name: "Shoulder Shrugs", type: "flexibility", sets: 1, reps: 10, notes: "Lift and release shoulders" },
      { name: "Wrist Circles", type: "flexibility", sets: 1, reps: 10, notes: "Both directions" },
    ],
  },
  {
    id: "tpl-077",
    name: "3-Minute Posture Fix",
    description: "Quick routine to counteract slouching and keyboard posture during work breaks.",
    category: "desk_break",
    durationMinutes: 3,
    exercises: [
      { name: "Chest Opener", type: "flexibility", sets: 1, reps: 1, durationMinutes: 0.5, notes: "Clasp hands behind back, lift" },
      { name: "Chin Tucks", type: "flexibility", sets: 1, reps: 10, notes: "Draw chin back, create double chin" },
      { name: "Seated Spinal Twist", type: "flexibility", sets: 1, reps: 1, durationMinutes: 0.5, notes: "Each side, hold the twist" },
      { name: "Standing Side Stretch", type: "flexibility", sets: 1, reps: 1, durationMinutes: 0.5, notes: "Each side, reach overhead" },
    ],
  },
  {
    id: "tpl-078",
    name: "Eye Strain Relief",
    description: "Gentle eye and face exercises to relieve screen fatigue during job searches.",
    category: "desk_break",
    durationMinutes: 3,
    exercises: [
      { name: "20-20-20 Rule", type: "other", sets: 1, reps: 1, durationMinutes: 1, notes: "Look 20 feet away for 20 seconds" },
      { name: "Eye Circles", type: "other", sets: 2, reps: 5, notes: "Slow circles with eyes only" },
      { name: "Palming", type: "other", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Rub hands warm, cover closed eyes" },
      { name: "Blinking Exercise", type: "other", sets: 1, reps: 20, notes: "Rapid blinking for 20 seconds" },
    ],
  },
  {
    id: "tpl-079",
    name: "3-Minute Energy Boost",
    description: "Quick standing movements to re-energize when motivation dips during job hunting.",
    category: "desk_break",
    durationMinutes: 3,
    exercises: [
      { name: "Jumping Jacks", type: "cardio", sets: 1, reps: 20, notes: "Get heart rate up quickly" },
      { name: "Standing Toe Touches", type: "flexibility", sets: 1, reps: 10, notes: "Alternate reaching for opposite toe" },
      { name: "High Knees in Place", type: "cardio", sets: 1, reps: 30, notes: "Drive knees high, pump arms" },
      { name: "Deep Breathing", type: "other", sets: 1, reps: 5, notes: "Inhale 4 counts, exhale 6 counts" },
    ],
  },
  {
    id: "tpl-080",
    name: "Wrist and Hand Relief",
    description: "Essential stretches for wrists and hands from extensive typing and mouse use.",
    category: "desk_break",
    durationMinutes: 3,
    exercises: [
      { name: "Wrist Flexor Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each arm, pull fingers back" },
      { name: "Wrist Extensor Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each arm, pull fingers down" },
      { name: "Prayer Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Press palms together, elbows out" },
      { name: "Finger Spreads", type: "flexibility", sets: 2, reps: 10, notes: "Spread fingers wide, make fist" },
    ],
  },
  {
    id: "tpl-081",
    name: "Lower Back Quick Fix",
    description: "Simple movements to relieve lower back stiffness from prolonged sitting.",
    category: "desk_break",
    durationMinutes: 3,
    exercises: [
      { name: "Standing Back Extension", type: "flexibility", sets: 3, reps: 5, notes: "Hands on lower back, lean back" },
      { name: "Seated Hip Flexor Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Sit at edge, one leg back" },
      { name: "Knee to Chest", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each leg, hug to chest while seated" },
    ],
  },
  {
    id: "tpl-082",
    name: "Standing Desk Break",
    description: "Quick standing routine for when you need a break from your chair between tasks.",
    category: "desk_break",
    durationMinutes: 4,
    exercises: [
      { name: "Standing Calf Raises", type: "strength", sets: 2, reps: 15, notes: "Rise onto toes, lower slowly" },
      { name: "Standing Quad Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each leg, hold for 15 seconds" },
      { name: "Standing Figure Four", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, ankle on knee, sit back" },
      { name: "Overhead Reach", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Reach high, lean side to side" },
    ],
  },
  {
    id: "tpl-083",
    name: "Stress Relief Micro-Break",
    description: "Calming breathing and movement exercises to reduce interview prep anxiety.",
    category: "desk_break",
    durationMinutes: 5,
    exercises: [
      { name: "Box Breathing", type: "other", sets: 4, reps: 1, durationMinutes: 0.5, notes: "Inhale 4, hold 4, exhale 4, hold 4" },
      { name: "Progressive Muscle Relaxation", type: "other", sets: 1, reps: 1, durationMinutes: 1, notes: "Tense and release each muscle group" },
      { name: "Neck and Shoulder Release", type: "flexibility", sets: 1, reps: 1, durationMinutes: 1, notes: "Gentle stretches, deep breathing" },
      { name: "Seated Butterfly Stretch", type: "flexibility", sets: 1, reps: 1, durationMinutes: 1, notes: "Soles together, gentle press on knees" },
    ],
  },
  {
    id: "tpl-084",
    name: "Hip Flexor Rescue",
    description: "Targeted routine to undo the damage of sitting all day during applications.",
    category: "desk_break",
    durationMinutes: 5,
    exercises: [
      { name: "Standing Hip Flexor Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, lunge position" },
      { name: "Seated Pigeon Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, ankle on opposite knee" },
      { name: "Standing Quad Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, pull heel to glute" },
      { name: "Glute Bridge", type: "strength", sets: 2, reps: 10, notes: "Lie on floor, squeeze at top" },
    ],
  },
  {
    id: "tpl-085",
    name: "5-Minute Full Reset",
    description: "Complete desk break routine addressing neck, shoulders, back, and hips.",
    category: "desk_break",
    durationMinutes: 5,
    exercises: [
      { name: "Neck Rolls", type: "flexibility", sets: 1, reps: 5, notes: "Slow, controlled circles" },
      { name: "Chest Opener", type: "flexibility", sets: 1, reps: 1, durationMinutes: 0.5, notes: "Clasp hands behind back" },
      { name: "Seated Twist", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, lengthen then rotate" },
      { name: "Standing Forward Fold", type: "flexibility", sets: 1, reps: 1, durationMinutes: 0.5, notes: "Let head hang heavy" },
      { name: "Standing Hip Flexor Stretch", type: "flexibility", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, lunge position" },
    ],
  },

  // ==========================================
  // CORE (10 templates, tpl-086 to tpl-095)
  // ==========================================
  {
    id: "tpl-086",
    name: "Plank Endurance Challenge",
    description: "Progressive plank holds to build core endurance and mental toughness.",
    category: "core",
    durationMinutes: 10,
    exercises: [
      { name: "Standard Plank", type: "strength", sets: 3, reps: 1, durationMinutes: 1, notes: "Hold body straight on forearms" },
      { name: "High Plank", type: "strength", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Arms straight, shoulders over wrists" },
      { name: "Side Plank", type: "strength", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Each side, stack feet" },
      { name: "Plank with Shoulder Taps", type: "strength", sets: 3, reps: 16, notes: "Alternate touching opposite shoulder" },
    ],
  },
  {
    id: "tpl-087",
    name: "Sit-Up Variety Pack",
    description: "Different sit-up variations to target all areas of the abdominal muscles.",
    category: "core",
    durationMinutes: 12,
    exercises: [
      { name: "Standard Sit-Ups", type: "strength", sets: 3, reps: 20, notes: "Full range, exhale on the way up" },
      { name: "Bicycle Crunches", type: "strength", sets: 3, reps: 24, notes: "Elbow to opposite knee" },
      { name: "Reverse Crunches", type: "strength", sets: 3, reps: 15, notes: "Lift hips off ground" },
      { name: "V-Ups", type: "strength", sets: 3, reps: 12, notes: "Reach hands to toes, body forms V" },
    ],
  },
  {
    id: "tpl-088",
    name: "Leg Raise Series",
    description: "Lower abdominal focused workout using leg raises with progressive difficulty.",
    category: "core",
    durationMinutes: 10,
    exercises: [
      { name: "Lying Leg Raises", type: "strength", sets: 3, reps: 15, notes: "Hands under hips, raise legs to 90" },
      { name: "Flutter Kicks", type: "strength", sets: 3, reps: 30, notes: "Small alternating kicks" },
      { name: "Scissor Kicks", type: "strength", sets: 3, reps: 20, notes: "Cross legs over each other" },
      { name: "Hanging Knee Raises", type: "strength", sets: 3, reps: 12, notes: "If bar available, or lying" },
    ],
  },
  {
    id: "tpl-089",
    name: "Ab Rollout Simulation",
    description: "Core workout mimicking ab wheel benefits using bodyweight movements.",
    category: "core",
    durationMinutes: 10,
    exercises: [
      { name: "Plank Walkouts", type: "strength", sets: 3, reps: 8, notes: "Walk hands out from standing" },
      { name: "Body Saw", type: "strength", sets: 3, reps: 12, notes: "Rock forward and back in plank" },
      { name: "Bear Plank Hold", type: "strength", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Knees hover 1 inch off ground" },
      { name: "Superman to Plank", type: "strength", sets: 3, reps: 10, notes: "Extend, then pull to plank" },
    ],
  },
  {
    id: "tpl-090",
    name: "Oblique Attack",
    description: "Targeted workout for the obliques to build a defined and functional midsection.",
    category: "core",
    durationMinutes: 12,
    exercises: [
      { name: "Russian Twists", type: "strength", sets: 4, reps: 24, notes: "Rotate torso side to side" },
      { name: "Side Plank Dips", type: "strength", sets: 3, reps: 15, notes: "Each side, lower and lift hips" },
      { name: "Bicycle Crunches", type: "strength", sets: 3, reps: 20, notes: "Slow and controlled" },
      { name: "Woodchoppers", type: "strength", sets: 3, reps: 12, notes: "Each side, diagonal chopping motion" },
      { name: "Windshield Wipers", type: "strength", sets: 3, reps: 12, notes: "Lie on back, legs side to side" },
    ],
  },
  {
    id: "tpl-091",
    name: "Six-Pack Shredder",
    description: "Intense ab circuit designed to target the rectus abdominis from multiple angles.",
    category: "core",
    durationMinutes: 15,
    exercises: [
      { name: "Crunches", type: "strength", sets: 4, reps: 25, notes: "Shoulder blades off ground" },
      { name: "Leg Raises", type: "strength", sets: 3, reps: 15, notes: "Lower back pressed to floor" },
      { name: "Bicycle Crunches", type: "strength", sets: 3, reps: 24, notes: "Alternate quickly" },
      { name: "Toe Touches", type: "strength", sets: 3, reps: 20, notes: "Legs straight up, reach for toes" },
      { name: "Dead Bug", type: "strength", sets: 3, reps: 12, notes: "Alternate arm and leg extension" },
    ],
  },
  {
    id: "tpl-092",
    name: "Anti-Rotation Core Work",
    description: "Core stability exercises that train your body to resist unwanted rotation.",
    category: "core",
    durationMinutes: 10,
    exercises: [
      { name: "Pallof Press", type: "strength", sets: 3, reps: 12, notes: "Each side, resist rotation" },
      { name: "Bird Dog", type: "strength", sets: 3, reps: 10, notes: "Each side, extend opposite arm and leg" },
      { name: "Single-Arm Farmer Carry", type: "strength", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Each side, walk with weight" },
      { name: "Plank with Arm Lift", type: "strength", sets: 3, reps: 10, notes: "Alternate lifting arms" },
    ],
  },
  {
    id: "tpl-093",
    name: "Lower Abs Blaster",
    description: "Focused lower abdominal workout for targeting the hard-to-reach area.",
    category: "core",
    durationMinutes: 8,
    exercises: [
      { name: "Reverse Crunches", type: "strength", sets: 4, reps: 15, notes: "Lift hips off ground" },
      { name: "Leg Lowers", type: "strength", sets: 3, reps: 12, notes: "Lower legs slowly, keep back flat" },
      { name: "Mountain Climbers", type: "cardio", sets: 3, reps: 20, notes: "Knees to chest, engage lower abs" },
      { name: "Toe Raises", type: "strength", sets: 3, reps: 15, notes: "Lie flat, raise legs to 90 degrees" },
    ],
  },
  {
    id: "tpl-094",
    name: "Core Stability Ball Workout",
    description: "Challenging core workout using a stability ball for enhanced engagement.",
    category: "core",
    durationMinutes: 15,
    exercises: [
      { name: "Ball Plank", type: "strength", sets: 3, reps: 1, durationMinutes: 1, notes: "Forearms on ball, hold plank" },
      { name: "Ball Pass", type: "strength", sets: 3, reps: 12, notes: "Pass ball from hands to feet" },
      { name: "Ball Rollout", type: "strength", sets: 3, reps: 10, notes: "Kneel, roll ball forward" },
      { name: "Ball Pike", type: "strength", sets: 3, reps: 10, notes: "Feet on ball, pike hips up" },
      { name: "Ball Crunch", type: "strength", sets: 3, reps: 15, notes: "Lower back on ball, crunch up" },
    ],
  },
  {
    id: "tpl-095",
    name: "Quick Core Blast",
    description: "Fast and effective core workout perfect for a time-crunched day.",
    category: "core",
    durationMinutes: 5,
    exercises: [
      { name: "Plank", type: "strength", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Hold as long as possible" },
      { name: "Bicycle Crunches", type: "strength", sets: 2, reps: 20, notes: "Fast but controlled" },
      { name: "Leg Raises", type: "strength", sets: 2, reps: 15, notes: "Lower back to floor" },
      { name: "Russian Twists", type: "strength", sets: 2, reps: 20, notes: "Fast rotation, feet off ground" },
    ],
  },

  // ==========================================
  // FULL_BODY (5 templates, tpl-096 to tpl-100)
  // ==========================================
  {
    id: "tpl-096",
    name: "Morning Full Body Circuit",
    description: "Energizing full body circuit mixing strength and cardio for a complete morning workout.",
    category: "full_body",
    durationMinutes: 25,
    exercises: [
      { name: "Jumping Jacks", type: "cardio", sets: 1, reps: 30, notes: "Get heart rate up" },
      { name: "Push-Ups", type: "strength", sets: 3, reps: 15, notes: "Standard form, full range" },
      { name: "Bodyweight Squats", type: "strength", sets: 3, reps: 20, notes: "Deep squats with good form" },
      { name: "Plank Hold", type: "strength", sets: 3, reps: 1, durationMinutes: 0.5, notes: "Tight core, flat back" },
      { name: "Lunges", type: "strength", sets: 3, reps: 16, notes: "Alternate legs" },
      { name: "Burpees", type: "cardio", sets: 3, reps: 8, notes: "Full burpee with push-up" },
    ],
  },
  {
    id: "tpl-097",
    name: "Lunch Break Express",
    description: "Quick full body workout you can do during a lunch break without needing a shower.",
    category: "full_body",
    durationMinutes: 15,
    exercises: [
      { name: "March in Place", type: "cardio", sets: 1, reps: 1, durationMinutes: 2, notes: "Warm up the body" },
      { name: "Wall Push-Ups", type: "strength", sets: 3, reps: 15, notes: "Easy on clothing" },
      { name: "Chair Squats", type: "strength", sets: 3, reps: 15, notes: "Sit and stand from chair" },
      { name: "Standing Side Leg Raises", type: "strength", sets: 3, reps: 12, notes: "Each leg, hold chair for balance" },
      { name: "Standing Calf Raises", type: "strength", sets: 3, reps: 15, notes: "Rise onto toes" },
      { name: "Desk Plank", type: "strength", sets: 2, reps: 1, durationMinutes: 0.5, notes: "Hands on desk, hold plank" },
    ],
  },
  {
    id: "tpl-098",
    name: "No-Equipment HIIT Circuit",
    description: "High-intensity full body circuit using only bodyweight for maximum calorie burn.",
    category: "full_body",
    durationMinutes: 30,
    exercises: [
      { name: "Burpees", type: "cardio", sets: 4, reps: 10, notes: "Explosive full body movement" },
      { name: "Mountain Climbers", type: "cardio", sets: 4, reps: 30, notes: "Fast pace, core tight" },
      { name: "Push-Ups", type: "strength", sets: 4, reps: 15, notes: "Standard or modified" },
      { name: "Jump Squats", type: "cardio", sets: 4, reps: 15, notes: "Land softly, explode up" },
      { name: "Plank Jacks", type: "cardio", sets: 4, reps: 20, notes: "Jump feet in and out" },
      { name: "High Knees", type: "cardio", sets: 4, reps: 30, notes: "Maximum effort" },
      { name: "Rest", type: "other", sets: 4, reps: 1, durationMinutes: 1, notes: "Walk in place, catch breath" },
    ],
  },
  {
    id: "tpl-099",
    name: "Strength and Cardio Fusion",
    description: "Alternating strength and cardio intervals for a balanced and challenging full body workout.",
    category: "full_body",
    durationMinutes: 40,
    exercises: [
      { name: "Jog in Place", type: "cardio", sets: 1, reps: 1, durationMinutes: 5, notes: "Warm up at moderate pace" },
      { name: "Dumbbell Squats", type: "strength", sets: 4, reps: 12, notes: "Hold dumbbells at sides" },
      { name: "Jump Rope", type: "cardio", sets: 4, reps: 1, durationMinutes: 1, notes: "Fast pace" },
      { name: "Dumbbell Rows", type: "strength", sets: 4, reps: 12, notes: "One arm at a time" },
      { name: "Jumping Jacks", type: "cardio", sets: 4, reps: 30, notes: "Full range of motion" },
      { name: "Dumbbell Shoulder Press", type: "strength", sets: 4, reps: 10, notes: "Seated or standing" },
      { name: "Mountain Climbers", type: "cardio", sets: 4, reps: 20, notes: "Fast pace" },
      { name: "Cool-Down Walk", type: "cardio", sets: 1, reps: 1, durationMinutes: 5, notes: "Easy pace, catch breath" },
    ],
  },
  {
    id: "tpl-100",
    name: "Ultimate Full Body Challenge",
    description: "Comprehensive full body workout combining bodyweight, cardio, and core for total fitness.",
    category: "full_body",
    durationMinutes: 35,
    exercises: [
      { name: "Jumping Jacks", type: "cardio", sets: 1, reps: 30, notes: "Warm up" },
      { name: "Push-Up Variations", type: "strength", sets: 3, reps: 15, notes: "Alternate wide, diamond, standard" },
      { name: "Squat to Lunge Combo", type: "strength", sets: 3, reps: 12, notes: "Squat then reverse lunge each leg" },
      { name: "Burpees", type: "cardio", sets: 3, reps: 10, notes: "Full burpee with jump" },
      { name: "Plank Series", type: "strength", sets: 3, reps: 1, durationMinutes: 1, notes: "Standard, side, reverse" },
      { name: "Plyometric Lunges", type: "cardio", sets: 3, reps: 16, notes: "Jump and switch legs" },
      { name: "Superman to Push-Up", type: "strength", sets: 3, reps: 10, notes: "Extend, then push-up" },
      { name: "Cool-Down Stretch", type: "flexibility", sets: 1, reps: 1, durationMinutes: 5, notes: "Full body stretch, deep breathing" },
    ],
  },
];
